[package]
name = "token"
version = "0.1.0"
authors = ["Vicki Niu <vicki.niu@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
byteorder = "1"
merlin = "3"
rand = "0.8"
subtle = "2"
curve25519-dalek = { version = "4", features = ["serde", "legacy_compatibility", "rand_core"] }

[dependencies.bulletproofs]
git = "https://github.com/runflame/bulletproofs"
branch = "develop"
features = ["yoloproofs"]

[dependencies.spacesuit]
path = "../spacesuit"

[dependencies.zkvm]
path = "../zkvm"

[dependencies.keytree]
path = "../keytree"

[dependencies.musig]
path = "../musig"
