[package]
name = "flame-minting"
version = "0.1.0"
edition = "2024"

[dependencies]
btc-integration = { path = "../btc-integration" }
flame-chain-service = { path = "../flame-chain-service" }
flamechain = { path = "../flamechain" }
flame-storage = { path = "../flame-storage" }
flamevm = { path = "../flamevm" }
tokio = { version = "1.53.1", features = ["macros", "rt", "sync"] }
tokio-util = { version = "0.7", features = ["rt"] }
corepc-client = { version = "0.16.0", features = ["client-sync"] }
log = "0.4.33"
thiserror = "2.0.19"

[dev-dependencies]
ed25519-dalek = "2"
