[package]
name = "btc-integration"
version = "0.1.0"
edition = "2024"

[dependencies]
corepc-client = { version = "0.16.0", features = ["client-sync"] }
curve25519-dalek = "4"
ed25519-dalek = "2"
flamevm = { path = "../flamevm" }
futures-util = "0.3"
serde_json = "1"
bitcoind = { version = "0.41", features = ["31_0", "download"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }
async-trait = "0.1.91"
thiserror = "2.0.19"
