[package]
name = "flamechain"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[features]
devnet = []

[dependencies]
cells = { path = "../cells" }
flamevm = { path = "../flamevm" }
hex = "0.3"
merkle = { path = "../merkle" }
merlin = "3"
readerwriter = { path = "../readerwriter" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
