[package]
name = "flamevm"
version = "0.1.0"
authors = ["Oleg Andreev <oleganza@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Flame virtual machine"

[dependencies]
curve25519-dalek = { version = "4", features = ["serde", "legacy_compatibility", "rand_core"] }
merlin = { version = "3" }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
sha3 = "0.10"
subtle = "2"
thiserror = "2.0.18"

[dependencies.readerwriter]
path = "../readerwriter"
features = ["merlin"]

[dependencies.merkle]
path = "../merkle"

[dependencies.bulletproofs]
git = "https://github.com/runflame/bulletproofs"
branch = "develop"
features = ["yoloproofs"]

[dependencies.spacesuit]
path = "../spacesuit"

[dependencies.musig]
path = "../musig"

[features]
default = []
nightly = ["curve25519-dalek/alloc", "bulletproofs/nightly"]
