use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use super::*;
use crate::{MAX_CELL_PAYLOAD, MAX_CELL_REFS};

// Minimum resources consumed by an inline value. References are never followed.
#[derive(Clone, Copy, Default)]
struct Size {
    bytes: usize,
    refs: usize,
    nesting: usize,
}

pub(super) fn generate(source: &str, decls: &[Decl]) -> Result<String, Error> {
    let mut compiler = Compiler {
        source,
        declarations: BTreeMap::new(),
        sizes: BTreeMap::new(),
        next_local: 0,
        used_locals: BTreeSet::new(),
        builder: String::new(),
        slice: String::new(),
        resolver: String::new(),
        resolver_type: String::new(),
    };
    for decl in decls {
        if compiler
            .declarations
            .insert(&decl.name.name, decl)
            .is_some()
        {
            return Err(Error::at(source, decl.name.offset, "duplicate type name"));
        }
    }
    for decl in decls {
        compiler.declaration_size(&decl.name, &mut BTreeSet::new(), 0)?;
    }
    for decl in decls {
        match &decl.kind {
            Kind::Struct(fields) => compiler.check_fields(fields)?,
            Kind::Enum { tag, variants } => {
                if variants.is_empty() {
                    return Err(Error::at(source, decl.name.offset, "enum needs a variant"));
                }
                let mut names = BTreeSet::new();
                let mut tags = BTreeSet::new();
                for variant in variants {
                    if !names.insert(&variant.name.name) || !tags.insert(variant.tag) {
                        return Err(Error::at(
                            source,
                            variant.name.offset,
                            "duplicate variant name or tag",
                        ));
                    }
                    if variant.tag > tag.max() {
                        return Err(Error::at(
                            source,
                            variant.name.offset,
                            "enum tag is out of range",
                        ));
                    }
                    compiler.check_fields(&variant.fields)?;
                }
            }
            Kind::Alias(ty) => compiler.check_type(ty, &BTreeMap::new())?,
        }
    }
    let mut output =
        String::from("// Generated by 🎻 CTL. Do not edit; change the .ctl source.\n\n");
    for decl in decls {
        compiler.emit_declaration(decl, &mut output);
    }
    Ok(imports(output, decls))
}

/// Import only names used by the codecs, with readable aliases for schema collisions.
fn imports(mut output: String, decls: &[Decl]) -> String {
    let mut used: BTreeSet<_> = decls.iter().map(|d| d.name.name.clone()).collect();
    let mut groups: [Vec<String>; 4] = std::array::from_fn(|_| Vec::new());
    for (path, name, alternative, group) in [
        ("::core::result::Result::Ok", "Ok", "StdOk", 0),
        ("::core::result::Result::Err", "Err", "StdErr", 0),
        ("::core::result::Result", "Result", "StdResult", 0),
        ("::core::marker::Sized", "Sized", "StdSized", 0),
        ("::std::vec::Vec", "Vec", "StdVec", 0),
        ("::cells::ctl::Ref", "Ref", "CellLink", 3),
        ("::cells::CellBuilder", "CellBuilder", "CellsBuilder", 2),
        ("::cells::CellDecode", "CellDecode", "CellsDecode", 2),
        ("::cells::CellEncode", "CellEncode", "CellsEncode", 2),
        ("::cells::CellError", "CellError", "CellsError", 2),
        ("::cells::CellRef", "CellRef", "CellsRef", 2),
        ("::cells::CellResolver", "CellResolver", "CellsResolver", 2),
        ("::cells::CellSlice", "CellSlice", "CellsSlice", 2),
        ("::core::primitive::usize", "usize", "Usize", 1),
    ] {
        if !output.contains(path) {
            continue;
        }
        let alias = if used.insert(name.into()) {
            name.to_owned()
        } else {
            let mut alias = alternative.to_owned();
            let mut suffix = 2;
            while !used.insert(alias.clone()) {
                alias = format!("{alternative}{suffix}");
                suffix += 1;
            }
            alias
        };
        output = output.replace(path, &alias);
        // Primitive names are already in scope unless shadowed by the schema.
        if name != "usize" || alias != name {
            groups[group].push(if alias == name {
                name.to_owned()
            } else {
                format!("{name} as {alias}")
            });
        }
    }
    let mut header = String::new();
    for (path, names) in [
        "::std::prelude::rust_2024",
        "::std::primitive",
        "::cells",
        "::cells::ctl",
    ]
    .into_iter()
    .zip(groups)
    {
        if !names.is_empty() {
            writeln!(header, "use {path}::{{{}}};", names.join(", ")).unwrap();
        }
    }
    // Keep the generated-file notice before the imports.
    let (notice, body) = output.split_once("\n\n").expect("generated notice");
    format!("{notice}\n\n{header}\n{body}")
}

struct Compiler<'a> {
    source: &'a str,
    declarations: BTreeMap<&'a str, &'a Decl>,
    sizes: BTreeMap<String, Size>,
    next_local: usize,
    used_locals: BTreeSet<String>,
    builder: String,
    slice: String,
    resolver: String,
    resolver_type: String,
}

impl Compiler<'_> {
    fn declaration(&self, name: &Ident) -> Result<&Decl, Error> {
        self.declarations
            .get(name.name.as_str())
            .copied()
            .ok_or_else(|| {
                Error::at(
                    self.source,
                    name.offset,
                    format!("unknown type `{}`", name.name),
                )
            })
    }

    fn declaration_size(
        &mut self,
        name: &Ident,
        active: &mut BTreeSet<String>,
        depth: usize,
    ) -> Result<Size, Error> {
        self.check_depth(depth, name.offset)?;
        if let Some(size) = self.sizes.get(&name.name) {
            self.check_depth(depth + size.nesting, name.offset)?;
            return Ok(*size);
        }
        if !active.insert(name.name.clone()) {
            return Err(Error::at(
                self.source,
                name.offset,
                "inline type cycle; use ^ for recursion",
            ));
        }
        let decl = self.declaration(name)?.clone();
        let mut size = match &decl.kind {
            Kind::Struct(fields) => self.fields_size(fields, active, depth + 1)?,
            Kind::Alias(ty) => self.type_size(ty, active, depth + 1)?,
            Kind::Enum { tag, variants } => {
                let mut minimum = Size {
                    bytes: usize::MAX,
                    refs: usize::MAX,
                    nesting: 0,
                };
                for variant in variants {
                    let mut size = self.fields_size(&variant.fields, active, depth + 1)?;
                    let tag_bytes = match tag {
                        Integer::V128 => {
                            (64 - variant.tag.leading_zeros()).max(1).div_ceil(7) as usize
                        }
                        _ => tag.bytes(),
                    };
                    size.bytes = size.bytes.saturating_add(tag_bytes);
                    self.check_capacity(size, variant.name.offset)?;
                    minimum.bytes = minimum.bytes.min(size.bytes);
                    minimum.refs = minimum.refs.min(size.refs);
                    minimum.nesting = minimum.nesting.max(size.nesting);
                }
                if variants.is_empty() {
                    Size::default()
                } else {
                    minimum
                }
            }
        };
        size.nesting += 1;
        self.check_depth(depth + size.nesting, name.offset)?;
        self.check_capacity(size, name.offset)?;
        active.remove(&name.name);
        self.sizes.insert(name.name.clone(), size);
        Ok(size)
    }

    fn fields_size(
        &mut self,
        fields: &[Field],
        active: &mut BTreeSet<String>,
        depth: usize,
    ) -> Result<Size, Error> {
        let mut total = Size::default();
        for field in fields {
            let size = self.type_size(&field.ty, active, depth)?;
            total.bytes = total.bytes.saturating_add(size.bytes);
            total.refs = total.refs.saturating_add(size.refs);
            total.nesting = total.nesting.max(size.nesting);
        }
        Ok(total)
    }

    fn type_size(
        &mut self,
        ty: &Ty,
        active: &mut BTreeSet<String>,
        depth: usize,
    ) -> Result<Size, Error> {
        self.check_depth(depth, ty.offset)?;
        let size = match &ty.kind {
            Type::Integer(integer) => Size {
                bytes: integer.bytes(),
                refs: 0,
                nesting: 1,
            },
            Type::Ref(name) => {
                if name.name != "Cell" {
                    self.declaration(name)?;
                }
                Size {
                    bytes: 0,
                    refs: 1,
                    nesting: 1,
                }
            }
            Type::Named(name) => self.declaration_size(name, active, depth)?,
            Type::Array(element, length) => {
                let size = self.type_size(element, active, depth + 1)?;
                if size.bytes == 0 && size.refs == 0 && !matches!(length, Length::Fixed(0)) {
                    return Err(Error::at(
                        self.source,
                        ty.offset,
                        "repeated elements must consume bytes or references",
                    ));
                }
                match length {
                    Length::Fixed(count) => Size {
                        bytes: size.bytes.saturating_mul(*count),
                        refs: size.refs.saturating_mul(*count),
                        nesting: size.nesting + 1,
                    },
                    Length::Field(_) => Size {
                        nesting: size.nesting + 1,
                        ..Size::default()
                    },
                }
            }
        };
        self.check_depth(depth + size.nesting, ty.offset)?;
        self.check_capacity(size, ty.offset)?;
        Ok(size)
    }

    fn check_depth(&self, depth: usize, offset: usize) -> Result<(), Error> {
        if depth > 128 {
            return Err(Error::at(
                self.source,
                offset,
                "inline type expansion exceeds 128 levels; use ^ references",
            ));
        }
        Ok(())
    }

    fn check_capacity(&self, size: Size, offset: usize) -> Result<(), Error> {
        if size.bytes > MAX_CELL_PAYLOAD || size.refs > MAX_CELL_REFS {
            return Err(Error::at(
                self.source,
                offset,
                "type cannot fit in one Cell; move fields behind ^ references",
            ));
        }
        Ok(())
    }

    fn check_fields(&self, fields: &[Field]) -> Result<(), Error> {
        let mut earlier = BTreeMap::new();
        for field in fields {
            if earlier.contains_key(field.name.name.as_str()) {
                return Err(Error::at(
                    self.source,
                    field.name.offset,
                    "duplicate field name",
                ));
            }
            self.check_type(&field.ty, &earlier)?;
            earlier.insert(field.name.name.as_str(), &field.ty);
        }
        Ok(())
    }

    fn check_type(&self, ty: &Ty, earlier: &BTreeMap<&str, &Ty>) -> Result<(), Error> {
        if let Type::Array(element, length) = &ty.kind {
            if let Length::Field(name) = length {
                let integer = earlier
                    .get(name.name.as_str())
                    .and_then(|ty| self.integer_wrappers(ty));
                if integer.is_none() {
                    return Err(Error::at(
                        self.source,
                        name.offset,
                        "array length must name an earlier unsigned integer field in this scope",
                    ));
                }
            }
            self.check_type(element, earlier)?;
        }
        Ok(())
    }

    // Alias declarations become transparent Rust newtypes, preserving codecs
    // such as V128 that would be lost by a plain Rust `type Count = u64`.
    fn integer_wrappers(&self, ty: &Ty) -> Option<usize> {
        match &ty.kind {
            Type::Integer(_) => Some(0),
            Type::Named(name) => match &self.declarations[name.name.as_str()].kind {
                Kind::Alias(inner) => self.integer_wrappers(inner).map(|n| n + 1),
                _ => None,
            },
            _ => None,
        }
    }

    fn rust_type(ty: &Ty) -> String {
        match &ty.kind {
            Type::Integer(integer) => integer.rust().into(),
            Type::Named(name) => name.name.clone(),
            Type::Ref(name) if name.name == "Cell" => "::cells::CellRef".into(),
            Type::Ref(name) => format!("::cells::ctl::Ref<{}>", name.name),
            Type::Array(element, Length::Fixed(count)) => {
                format!("[{}; {count}]", Self::rust_type(element))
            }
            Type::Array(element, Length::Field(_)) => {
                format!("::std::vec::Vec<{}>", Self::rust_type(element))
            }
        }
    }

    fn local(&mut self) -> String {
        const NAMES: &[&str] = &[
            "x", "y", "z", "n", "v", "i", "j", "k", "l", "m", "c", "d", "e", "f", "g", "h", "o",
            "p", "q", "r", "s", "t", "u", "w",
        ];
        loop {
            let index = self.next_local;
            self.next_local += 1;
            let name = if index < NAMES.len() {
                NAMES[index].to_owned()
            } else {
                format!("x{}", index - NAMES.len() + 1)
            };
            if self.used_locals.insert(name.clone()) {
                return name;
            }
        }
    }

    fn parameter(&mut self, name: &str) -> String {
        let mut candidate = name.to_owned();
        let mut suffix = 1;
        while !self.used_locals.insert(candidate.clone()) {
            candidate = format!("{name}{suffix}");
            suffix += 1;
        }
        candidate
    }

    fn reset_locals(&mut self) {
        self.next_local = 0;
        self.used_locals = self
            .declarations
            .keys()
            .map(|name| (*name).to_owned())
            .collect();
    }

    fn uses_resolver(ty: &Ty) -> bool {
        match &ty.kind {
            Type::Named(_) => true,
            Type::Ref(name) => name.name != "Cell",
            Type::Array(_, Length::Fixed(0)) | Type::Integer(_) => false,
            Type::Array(element, _) => Self::uses_resolver(element),
        }
    }

    fn needs_cursor(decl: &Decl) -> bool {
        match &decl.kind {
            Kind::Alias(ty) => !matches!(ty.kind, Type::Array(_, Length::Fixed(0))),
            Kind::Struct(fields) => fields
                .iter()
                .any(|f| !matches!(f.ty.kind, Type::Array(_, Length::Fixed(0)))),
            Kind::Enum { .. } => true,
        }
    }

    fn needs_resolver(decl: &Decl) -> bool {
        match &decl.kind {
            Kind::Alias(ty) => Self::uses_resolver(ty),
            Kind::Struct(fields) => fields.iter().any(|f| Self::uses_resolver(&f.ty)),
            Kind::Enum { variants, .. } => variants
                .iter()
                .flat_map(|v| &v.fields)
                .any(|f| Self::uses_resolver(&f.ty)),
        }
    }

    fn emit_declaration(&mut self, decl: &Decl, out: &mut String) {
        let name = &decl.name.name;
        writeln!(
            out,
            "#[derive(Clone, Debug)]\n#[allow(non_camel_case_types, non_snake_case)]"
        )
        .unwrap();
        match &decl.kind {
            Kind::Struct(fields) => {
                writeln!(out, "pub struct {name} {{").unwrap();
                for field in fields {
                    writeln!(
                        out,
                        "pub {}: {},",
                        field.name.name,
                        Self::rust_type(&field.ty)
                    )
                    .unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
            Kind::Enum { variants, .. } => {
                writeln!(out, "pub enum {name} {{").unwrap();
                for variant in variants {
                    write!(out, "{}", variant.name.name).unwrap();
                    if !variant.fields.is_empty() {
                        write!(out, " {{").unwrap();
                        for field in &variant.fields {
                            write!(out, "{}: {},", field.name.name, Self::rust_type(&field.ty))
                                .unwrap();
                        }
                        write!(out, "}}").unwrap();
                    }
                    writeln!(out, ",").unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
            Kind::Alias(ty) => {
                writeln!(out, "pub struct {name}(pub {});", Self::rust_type(ty)).unwrap()
            }
        }
        self.reset_locals();
        self.builder = self.parameter("b");
        let builder = if Self::needs_cursor(decl) {
            self.builder.as_str()
        } else {
            "_"
        };
        writeln!(out, "impl ::cells::CellEncode for {name} {{\nfn encode(&self, {builder}: &mut ::cells::CellBuilder) -> ::core::result::Result<(), ::cells::CellError> {{").unwrap();
        match &decl.kind {
            Kind::Struct(fields) => self.encode_fields(fields, "Self", out),
            Kind::Alias(ty) => out.push_str(&self.encode(ty, "&self.0", &BTreeMap::new())),
            Kind::Enum { tag, variants } => {
                writeln!(out, "match self {{").unwrap();
                for variant in variants {
                    let path = format!("Self::{}", variant.name.name);
                    // Bind fields once so their values can also size later arrays.
                    let bindings = self.bindings(&variant.fields, true);
                    writeln!(
                        out,
                        "{} => {{",
                        Self::pattern(&path, &variant.fields, &bindings)
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "{}.store_{}({})?;",
                        self.builder,
                        tag.method(),
                        variant.tag
                    )
                    .unwrap();
                    for field in &variant.fields {
                        out.push_str(&self.encode(
                            &field.ty,
                            &bindings[&field.name.name].0,
                            &bindings,
                        ));
                    }
                    writeln!(out, "}},").unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
        }
        writeln!(out, "::core::result::Result::Ok(())\n}}\n}}").unwrap();
        self.reset_locals();
        self.slice = self.parameter("a");
        self.resolver = self.parameter("b");
        self.resolver_type = self.parameter("R");
        let resolver = if Self::needs_resolver(decl) {
            self.resolver.as_str()
        } else {
            "_"
        };
        let cursor = if Self::needs_cursor(decl) {
            self.slice.as_str()
        } else {
            "_"
        };
        writeln!(out, "impl ::cells::CellDecode for {name} {{\nfn decode<{}: ::cells::CellResolver + ?::core::marker::Sized>({}: &mut ::cells::CellSlice<'_>, {resolver}: &mut {}) -> ::core::result::Result<Self, ::cells::CellError> {{\n{}.try_load(|{cursor}| {{", self.resolver_type, self.slice, self.resolver_type, self.slice).unwrap();
        match &decl.kind {
            Kind::Struct(fields) => self.decode_fields(fields, "Self", out),
            Kind::Alias(ty) => writeln!(
                out,
                "::core::result::Result::Ok(Self({}))",
                self.decode(ty, &BTreeMap::new())
            )
            .unwrap(),
            Kind::Enum { tag, variants } => {
                writeln!(
                    out,
                    "#[allow(unreachable_patterns)]\nmatch {}.load_{}()? {{",
                    self.slice,
                    tag.method()
                )
                .unwrap();
                for variant in variants {
                    writeln!(out, "{} => {{", variant.tag).unwrap();
                    self.decode_fields(
                        &variant.fields,
                        &format!("Self::{}", variant.name.name),
                        out,
                    );
                    writeln!(out, "}},").unwrap();
                }
                writeln!(
                    out,
                    "_ => ::core::result::Result::Err(::cells::CellError::InvalidFormat),\n}}"
                )
                .unwrap();
            }
        }
        writeln!(out, "}})\n}}\n}}\n").unwrap();
    }

    fn bindings<'a>(
        &mut self,
        fields: &'a [Field],
        encode: bool,
    ) -> BTreeMap<String, (String, &'a Ty, bool)> {
        fields
            .iter()
            .map(|field| (field.name.name.clone(), (self.local(), &field.ty, encode)))
            .collect()
    }

    fn pattern(
        path: &str,
        fields: &[Field],
        bindings: &BTreeMap<String, (String, &Ty, bool)>,
    ) -> String {
        if fields.is_empty() && path != "Self" {
            return path.into();
        }
        let fields = fields
            .iter()
            .map(|f| format!("{}: {},", f.name.name, bindings[&f.name.name].0))
            .collect::<String>();
        format!("{path} {{ {fields} }}")
    }

    fn encode_fields(&mut self, fields: &[Field], path: &str, out: &mut String) {
        let bindings = self.bindings(fields, true);
        writeln!(
            out,
            "let {} = self;",
            Self::pattern(path, fields, &bindings)
        )
        .unwrap();
        for field in fields {
            out.push_str(&self.encode(&field.ty, &bindings[&field.name.name].0, &bindings));
        }
    }

    fn decode_fields(&mut self, fields: &[Field], path: &str, out: &mut String) {
        let bindings = self.bindings(fields, false);
        for field in fields {
            writeln!(
                out,
                "let {}: {} = {};",
                bindings[&field.name.name].0,
                Self::rust_type(&field.ty),
                self.decode(&field.ty, &bindings)
            )
            .unwrap();
        }
        writeln!(
            out,
            "::core::result::Result::Ok({})",
            Self::pattern(path, fields, &bindings)
        )
        .unwrap();
    }

    fn count(&self, length: &Length, bindings: &BTreeMap<String, (String, &Ty, bool)>) -> String {
        match length {
            Length::Fixed(n) => format!("{n}usize"),
            Length::Field(name) => {
                let (local, ty, encode) = &bindings[&name.name];
                let wrappers = self.integer_wrappers(ty).expect("validated count");
                let mut value = if *encode && wrappers == 0 {
                    format!("*{local}")
                } else {
                    local.clone()
                };
                for _ in 0..wrappers {
                    value.push_str(".0");
                }
                format!(
                    "::core::primitive::usize::try_from({value}).map_err(|_| ::cells::CellError::LimitExceeded)?"
                )
            }
        }
    }

    fn array_guard(&mut self, element: &Ty, count: &str, encode: bool) -> String {
        let size = self
            .type_size(element, &mut BTreeSet::new(), 0)
            .expect("validated type");
        let mut out = String::new();
        let (cursor, byte_error, ref_error) = if encode {
            (
                self.builder.as_str(),
                "PayloadCapacity",
                "ReferenceCapacity",
            )
        } else {
            (
                self.slice.as_str(),
                "InsufficientBytes",
                "InsufficientReferences",
            )
        };
        for (minimum, remaining, error) in [
            (size.bytes, "remaining_bytes", byte_error),
            (size.refs, "remaining_refs", ref_error),
        ] {
            if minimum > 0 {
                let available = if minimum == 1 {
                    format!("{cursor}.{remaining}()")
                } else {
                    format!("{cursor}.{remaining}() / {minimum}")
                };
                writeln!(out, "if {count} > {available} {{ return ::core::result::Result::Err(::cells::CellError::{error}); }}").unwrap();
            }
        }
        out
    }

    fn encode(
        &mut self,
        ty: &Ty,
        value: &str,
        bindings: &BTreeMap<String, (String, &Ty, bool)>,
    ) -> String {
        match &ty.kind {
            Type::Integer(integer) => {
                let value = value
                    .strip_prefix('&')
                    .map(str::to_owned)
                    .unwrap_or_else(|| format!("*{value}"));
                format!("{}.store_{}({value})?;\n", self.builder, integer.method())
            }
            Type::Named(_) => format!("::cells::CellEncode::encode({value}, {})?;\n", self.builder),
            Type::Ref(name) if name.name == "Cell" => {
                let value = value.strip_prefix('&').unwrap_or(value);
                format!("{}.store_ref({value}.clone())?;\n", self.builder)
            }
            Type::Ref(_) => format!("::cells::CellEncode::encode({value}, {})?;\n", self.builder),
            Type::Array(_, Length::Fixed(0)) => format!("let _ = {value};\n"),
            Type::Array(element, length) => {
                let count = self.local();
                let mut out = format!("let {count} = {};\n", self.count(length, bindings));
                if matches!(length, Length::Field(_)) {
                    let array = value.strip_prefix('&').unwrap_or(value);
                    writeln!(out, "if {array}.len() != {count} {{ return ::core::result::Result::Err(::cells::CellError::InvalidFormat); }}").unwrap();
                }
                out.push_str(&self.array_guard(element, &count, true));
                if matches!(element.kind, Type::Integer(Integer::U8)) {
                    writeln!(out, "{}.store_bytes({value})?;", self.builder).unwrap();
                } else {
                    let item = self.local();
                    let array = value.strip_prefix('&').unwrap_or(value);
                    writeln!(out, "for {item} in {array}.iter() {{").unwrap();
                    out.push_str(&self.encode(element, &item, bindings));
                    writeln!(out, "}}").unwrap();
                }
                out
            }
        }
    }

    fn decode(&mut self, ty: &Ty, bindings: &BTreeMap<String, (String, &Ty, bool)>) -> String {
        match &ty.kind {
            Type::Integer(integer) => format!("{}.load_{}()?", self.slice, integer.method()),
            Type::Named(name) => format!(
                "<{} as ::cells::CellDecode>::decode({}, {})?",
                name.name, self.slice, self.resolver
            ),
            Type::Ref(name) if name.name == "Cell" => format!("{}.load_ref()?", self.slice),
            Type::Ref(_) => format!(
                "<{} as ::cells::CellDecode>::decode({}, {})?",
                Self::rust_type(ty),
                self.slice,
                self.resolver
            ),
            Type::Array(_, Length::Fixed(0)) => "[]".into(),
            Type::Array(element, length) => {
                let count = self.local();
                let mut out = format!("{{\nlet {count} = {};\n", self.count(length, bindings));
                out.push_str(&self.array_guard(element, &count, false));
                if matches!(element.kind, Type::Integer(Integer::U8)) {
                    write!(out, "{}.load_bytes({count})?", self.slice).unwrap();
                    if matches!(length, Length::Fixed(_)) {
                        out.push_str(".try_into().map_err(|_| ::cells::CellError::InvalidFormat)?");
                    } else {
                        out.push_str(".to_vec()");
                    }
                } else {
                    let values = self.local();
                    writeln!(
                        out,
                        "let mut {values} = ::std::vec::Vec::new();\nfor _ in 0..{count} {{"
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "{values}.push({});\n}}",
                        self.decode(element, bindings)
                    )
                    .unwrap();
                    out.push_str(&values);
                    if matches!(length, Length::Fixed(_)) {
                        out.push_str(".try_into().map_err(|_| ::cells::CellError::InvalidFormat)?");
                    }
                }
                out.push_str("\n}");
                out
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::super::compile;

    #[test]
    fn rejects_invalid_schemas() {
        for (source, reason) in [
            ("struct A {} struct A {}", "duplicate"),
            ("struct A { x: Missing }", "unknown"),
            ("struct A { x: A }", "cycle"),
            ("type A = B; type B = A;", "cycle"),
            ("struct A { x: U8, x: U16 }", "duplicate"),
            ("struct A { b: [U8; n], n: U8 }", "earlier"),
            ("struct A { n: [U8; 2], b: [U8; n] }", "earlier"),
            ("type A = [U8; n];", "earlier"),
            ("enum A: U8 {}", "variant"),
            ("enum A: U8 { X=1, Y=1 }", "duplicate"),
            ("enum A: U8 { X=256 }", "range"),
            ("struct A { x: [U8; 4096] }", "fit"),
            ("struct A { x: [^Cell; 5] }", "fit"),
            ("type A = [[U64; 18446744073709551615]; 0];", "fit"),
            ("struct A { n:U8, a:[[U64;18446744073709551615];n] }", "fit"),
            ("enum A: V128 { X { x: [U8; 4094] } = 128 }", "fit"),
            ("struct E {} struct A { n:U64, a:[E;n] }", "consume"),
            ("struct E {} type A = [E; 999999];", "consume"),
            ("struct A { x: Cell }", "unknown"),
            ("type A = u8;", "unknown"),
            ("type A = u16;", "unknown"),
            ("type A = u32;", "unknown"),
            ("type A = u64;", "unknown"),
            ("type A = leb128;", "unknown"),
        ] {
            let error = compile(source).expect_err(source);
            assert!(error.message.contains(reason), "{source}: {error}");
            assert!(error.line > 0 && error.column > 0);
        }
    }

    #[test]
    fn supports_forward_names_recursive_refs_and_codec_aliases() {
        let output = compile("type Count = V128; struct A { n: Count, data: [U16; n], next: ^B } enum B: U8 { End=0, More { a:^A }=1 }").unwrap();
        assert!(output.contains("pub struct Count(pub u64)"));
        assert!(output.contains("store_leb128"));
        assert!(output.contains("Ref<B>"));
        assert!(!output.contains("__ctl_"));
        assert!(output.contains("remaining_bytes() / 2"));
        assert!(output.contains(".0).map_err"));
    }

    #[test]
    fn all_wire_types_generate_definitions_and_codecs() {
        let source = "type Point=[U8;32]; struct Points { n:U8, points:[Point;n], next:^Point }";
        let output = compile(source).unwrap();
        assert!(output.contains("pub struct Point(pub [u8; 32])"));
        assert!(output.contains("impl CellEncode for Point"));
        assert!(output.contains("impl CellDecode for Point"));
        assert!(output.contains("Vec<Point>"));
        assert!(output.contains("Ref<Point>"));
        assert!(output.contains("<Point as CellDecode>::decode"));
        assert!(output.contains("remaining_bytes() / 32"));
        assert!(output.contains("CellEncode::encode"));
        assert!(compile("type Point=[U8;32]; struct TooBig { points:[Point;128] }").is_err());
    }

    #[test]
    fn combined_named_and_array_nesting_is_bounded_in_either_order() {
        let declarations: Vec<_> = (0..256)
            .map(|i| {
                let next = if i == 255 {
                    "U8".into()
                } else {
                    format!("A{}", i + 1)
                };
                format!("type A{i} = {}{next}{};", "[".repeat(64), ";1]".repeat(64))
            })
            .collect();
        for source in [
            declarations.join("\n"),
            declarations
                .into_iter()
                .rev()
                .collect::<Vec<_>>()
                .join("\n"),
        ] {
            assert!(compile(&source).unwrap_err().message.contains("expansion"));
        }
    }
}
