name: Source code health

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cargo test
      run: cargo test

  cargo-bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build benchmarks
      run: RUSTFLAGS="-C opt-level=0" cargo bench DONTRUNBENCHMARKS
